global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "jenkins"
    metrics_path: "/prometheus"
    scheme: http
    static_configs:
      - targets: ["localhost:8080"]

  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus:9090"]
