apiVersion: v1
kind: LimitRange
metadata:
  name: resource-constrant
  namespace: staging
spec:
  limits:
  - default:
      memory: 500Mi
    defaultRequest:
      cpu: 100m
      memory: 500Mi
    max:
      memory: 2Gi
    min:
      cpu: 100m
      memory: 500Mi
    type: Container