apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-deploy
  namespace: staging
  labels:
    app: streaming-app
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: streaming-app
  template:
    metadata:
      labels:
        app: streaming-app
    spec:
      containers:
       - name: postgres
         image: postgres
         imagePullPolicy: Always
         ports:
         - containerPort: 5432
         env:
         - name: POSTGRES_USER
           value: "postgres"
         - name: POSTGRES_PASSWORD
           value: "postgres"
         volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi